stages:
  train:
    cmd: python train.py
    deps:
    - data
    - train.py
    outs:
    - model.weights.h5
    metrics:
    - metrics.csv:
        cache: false
  train_live:
    cmd: python train_live.py
    deps:
    - data
    - train_live.py
    outs:
    - model_live.weights.h5
    - mymodel_live.h5
    metrics:
    - metrics_live.csv:
        cache: false
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
artifacts:
  mymodel_live:
    path: mymodel_live.h5
    type: model
